In [1]:
import pandas as pd
import os
cur_dir = os.getcwd()
cur_dir

'/Users/garrettroell/Documents/VS_code_projects/machine_learning_clostridium/lib'

In [2]:
raw_data_6 = pd.read_csv(f'{cur_dir}/data/raw_data_6.csv')
raw_data_6.set_index(['composition','trial','time'],drop=True,inplace=True)

smooth_data_6 = pd.read_csv(f'{cur_dir}/data/smooth_data_6.csv')
smooth_data_6.set_index(['composition','trial','time'],drop=True,inplace=True)

raw_data_7 = pd.read_csv(f'{cur_dir}/data/raw_data_7.csv')
raw_data_7.set_index(['composition','trial','time'],drop=True,inplace=True)

smooth_data_7 = pd.read_csv(f'{cur_dir}/data/smooth_data_7.csv')
smooth_data_7.set_index(['composition','trial','time'],drop=True,inplace=True)

In [3]:
display(raw_data_6.head())
display(smooth_data_7.head())

acetate  biomass  butanol  butyrate  ethanol  \
composition trial time                                                 
1           1     0.58    21.61     0.41     0.04      0.06    10.94   
                  0.65    44.31     0.39     0.05      0.08    15.89   
                  1.02    46.19     0.46     0.21      0.64     8.14   
                  1.67    46.16     0.49     1.18      3.64    10.81   
                  3.70    34.39     0.64     8.44      9.76    20.34   

                        flow rate     H2   CO    CO2  acetate_0  biomass_0  \
composition trial time                                                       
1           1     0.58         20  0.125  0.5  0.375  16.905029   0.429546   
                  0.65         20  0.125  0.5  0.375  16.905029   0.429546   
                  1.02         20  0.125  0.5  0.375  16.905029   0.429546   
                  1.67         20  0.125  0.5  0.375  16.905029   0.429546   
                  3.70         20  0.125  0.5  0.375  16.905029   0.429546   

                        butanol_0  butyrate_0  ethanol_0   acetate_Δ  \
composition trial time                                                 
1           1     0.58   0.029818    0.075529   15.89524    0.000000   
                  0.65   0.029818    0.075529   15.89524  324.285714   
                  1.02   0.029818    0.075529   15.89524    5.081081   
                  1.67   0.029818    0.075529   15.89524   -0.046154   
                  3.70   0.029818    0.075529   15.89524   -5.798030   

                        biomass_Δ  butanol_Δ  butyrate_Δ  ethanol_Δ  
composition trial time                                               
1           1     0.58   0.000000   0.000000    0.000000   0.000000  
                  0.65  -0.285714   0.142857    0.285714  70.714286  
                  1.02   0.189189   0.432432    1.513514 -20.945946  
                  1.67   0.046154   1.492308    4.615385   4.107692  
                  3.70   0.073892   3.576355    3.014778   4.694581

CO    CO2     H2    acetate   biomass   butanol  \
composition trial time                                                     
1           1     0.0   0.5  0.375  0.125  16.905029  0.429546  0.029818   
                  0.1   0.5  0.375  0.125  18.001195  0.421076  0.028260   
                  0.2   0.5  0.375  0.125  19.831073  0.410803  0.028316   
                  0.3   0.5  0.375  0.125  22.196249  0.403602  0.031357   
                  0.4   0.5  0.375  0.125  25.293925  0.403709  0.028700   

                        butyrate    ethanol  flow rate  acetate_0  biomass_0  \
composition trial time                                                         
1           1     0.0   0.075529  15.895240       20.0  16.905029   0.429546   
                  0.1   0.061033  15.607023       20.0  16.905029   0.429546   
                  0.2   0.051013  15.144135       20.0  16.905029   0.429546   
                  0.3   0.050367  14.522308       20.0  16.905029   0.429546   
                  0.4   0.035514  13.956015       20.0  16.905029   0.429546   

                        butanol_0  butyrate_0  ethanol_0  acetate_Δ  \
composition trial time                                                
1           1     0.0    0.029818    0.075529   15.89524   0.000000   
                  0.1    0.029818    0.075529   15.89524  10.961665   
                  0.2    0.029818    0.075529   15.89524  18.298778   
                  0.3    0.029818    0.075529   15.89524  23.651756   
                  0.4    0.029818    0.075529   15.89524  30.976760   

                        biomass_Δ  butanol_Δ  butyrate_Δ  ethanol_Δ  
composition trial time                                               
1           1     0.0    0.000000   0.000000    0.000000   0.000000  
                  0.1   -0.084697  -0.015584   -0.144950  -2.882172  
                  0.2   -0.102733   0.000561   -0.100208  -4.628878  
                  0.3   -0.072009   0.030416   -0.006462  -6.218271  
                  0.4    0.001068  -0.026579   -0.148525  -5.662923

In [4]:
from machine_learning.get_trained_models import get_trained_models_slope_6, get_trained_models_slope_7

trained_models_6 = get_trained_models_slope_6(raw_data_6, smooth_data_6)
trained_models_7 = get_trained_models_slope_7(raw_data_7, smooth_data_7)

raw
gradient boosting
raw, gradient boosting, comp excluded from training: none
raw, gradient boosting, comp excluded from training: 1
raw, gradient boosting, comp excluded from training: 2
raw, gradient boosting, comp excluded from training: 3
raw, gradient boosting, comp excluded from training: 4
raw, gradient boosting, comp excluded from training: 5
raw, gradient boosting, comp excluded from training: 6
random forest
raw, random forest, comp excluded from training: none
raw, random forest, comp excluded from training: 1
raw, random forest, comp excluded from training: 2
raw, random forest, comp excluded from training: 3
raw, random forest, comp excluded from training: 4
raw, random forest, comp excluded from training: 5
raw, random forest, comp excluded from training: 6
support vector
raw, support vector, comp excluded from training: none
raw, support vector, comp excluded from training: 1
raw, support vector, comp excluded from training: 2
raw, support vector, comp excluded from tr

In [123]:
model = trained_models_6['gradient boosting, raw, test comp = none']

In [160]:
import numpy as np

def get_ml_model_derivs(t, y, gas_comp, ml_model):

    dy = []
    # makes sure all values are non-negative
    for counter,conc in enumerate(y,0):
        if conc < 0:
            y[counter] = 0
    
    # the asterisks unpacks the contents of iterables
    ml_input_list = [[*[t], *y, *gas_comp]]
    ml_input_array = np.array(ml_input_list)
    # print(ml_model.predict(ml_input_array))

    for slope in ml_model.predict(ml_input_array)[0]:
        if slope > 100:
            slope = 100
        if slope < -100:
            slope = -100
        dy.append(slope)
        
    return dy 

In [161]:
# t_test = 0
# y_test = [16.90502895927611, 0.4295457013574683, 0.029818099547511474, 0.07552850678733072, 15.895239819004606]
# gas_comp_test = [0.5000000000000027, 0.3750000000000019, 0.12500000000000067, 20.00000000000011]
# ml_model_test = model


# get_ml_model_derivs(t_test, y_test, gas_comp_test, ml_model_test)

[[1.26993472e+01 2.25988335e-03 2.08653632e-01 6.34617367e-01
  7.38477454e+00]]


[12.699347183416105,
 0.0022598833467964846,
 0.20865363163133205,
 0.6346173669833871,
 7.38477454308228]

In [182]:
from scipy.integrate import solve_ivp

def solve_diff_eqs_ml(initial_values, t_range, times_list, gas_comp, ml_model):
   
    # t_range = [times[0],times[-1]]
    sol = solve_ivp(lambda t, y: get_ml_model_derivs(t, y, gas_comp, ml_model), t_range, initial_values, t_eval=times_list, rtol = 0.01, atol = 0.01)

    sim_data = pd.DataFrame(index = t_range, columns = ['acetate','biomass', 'butanol', 'butyrate', 'ethanol'])

    sim_data['acetate']  = sol.y[0]
    sim_data['biomass']  = sol.y[1]
    sim_data['butanol']  = sol.y[2]
    sim_data['butyrate'] = sol.y[3]
    sim_data['ethanol']  = sol.y[4]
    sim_data.clip(lower=0, inplace=True)

    return sim_data 

In [185]:
initial_values_test = [16.90502895927611, 0.4295457013574683, 0.029818099547511474, 0.07552850678733072, 15.895239819004606]
t_range_test = [0, 5.6]
gas_comp_test = [0.5000000000000027, 0.3750000000000019, 0.12500000000000067, 20.00000000000011]
ml_model_test = model
time_list_test = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6]

solve_diff_eqs_ml(initial_values_test, t_range_test, time_list_test, gas_comp_test, ml_model_test)

[[1.26993472e+01 2.25988335e-03 2.08653632e-01 6.34617367e-01
  7.38477454e+00]]
[[1.26993472e+01 2.25988335e-03 2.08653632e-01 6.34617367e-01
  7.38477454e+00]]
[[1.26993472e+01 2.25988335e-03 2.08653632e-01 6.41660845e-01
  7.38477454e+00]]
[[1.26993472e+01 2.25988335e-03 2.08653632e-01 6.41660845e-01
  7.38477454e+00]]
[[12.69934718  0.02076015  0.27619806  0.64166085  7.38477454]]
[[11.16920365  0.02076015  0.27619806  0.64166085  7.38477454]]
[[11.16920365  0.02076015  0.27619806  0.64166085  7.38477454]]
[[11.16920365  0.02076015  0.27619806  0.64166085  7.38477454]]
[[11.16920365  0.02076015  0.28073034  0.64166085  7.38477454]]
[[11.16920365  0.02076015  0.28073034  0.64166085  7.38477454]]
[[11.16920365  0.02076015  0.29700704  0.64166085  7.38477454]]
[[11.16920365  0.02076015  0.29700704  0.64166085  7.38477454]]
[[11.16920365  0.02076015  0.40704838  0.60890005  7.38477454]]
[[11.16920365  0.02076015  0.40704838  0.60890005  7.38477454]]
[[11.16920365  0.03436858  0.4645677

ValueError: Length of values (57) does not match length of index (2)

In [ ]:
def get_model_predictions_6_slope(model_dict, input_df):
    model_predictions = {}
    ml_input, _ = get_X_y_arrays_conc(input_df, [1, 2, 3, 4, 5, 6, 7, 8, 9])

    for model_name in model_dict.keys():
        model = model_dict[model_name]

        prediction_df = get_slope_prediction_df()
        prediction = model.predict(ml_input)
        prediction_df = pd.DataFrame(data=prediction, index=input_df.index, columns=['acetate', 'biomass', 'butanol', 'butyrate', 'ethanol'])
        model_predictions[model_name] = prediction_df

    return model_predictions

In [9]:
# from machine_learning.get_model_predictions import get_model_predictions_6, get_model_predictions_7
measured_time_predictions_6 = get_model_predictions_6_slope(trained_models_6, raw_data_6)
# smoothed_time_predictions_6 = get_model_predictions_6(trained_models_6, smooth_data_6)

# measured_time_predictions_7 = get_model_predictions_7(trained_models_7, raw_data_7)
# smoothed_time_predictions_7 = get_model_predictions_7(trained_models_7, smooth_data_7)

NameError: name 'get_X_y_arrays_conc' is not defined

In [177]:
# works
def get_only_starting_values (smooth_df):
    df = smooth_df.reset_index(inplace=False, drop=False)
    df = df[df['time'] == 0]
    df.set_index(['composition', 'trial', 'time'], drop=True, inplace=True)
    return df

# works
def get_time_range(smooth_df, composition, trial):
    df = smooth_df.reset_index(inplace=False, drop=False)
    df = df[df['composition'] == composition]
    df = df[df['trial'] == trial]

    time_range = [0, max(df['time'])]
    return time_range

def get_times(smooth_df, composition, trial):
    df = smooth_df.reset_index(inplace=False, drop=False)
    df = df[df['composition'] == composition]
    df = df[df['trial'] == trial]

    time_list = list(df['time'])
    return time_list

In [178]:

get_times(smooth_data_6, 1, 1)
       

[0.0,
 0.1,
 0.2,
 0.3,
 0.4,
 0.5,
 0.6,
 0.7,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2,
 1.3,
 1.4,
 1.5,
 1.6,
 1.7,
 1.8,
 1.9,
 2.0,
 2.1,
 2.2,
 2.3,
 2.4,
 2.5,
 2.6,
 2.7,
 2.8,
 2.9,
 3.0,
 3.1,
 3.2,
 3.3,
 3.4,
 3.5,
 3.6,
 3.7,
 3.8,
 3.9,
 4.0,
 4.1,
 4.2,
 4.3,
 4.4,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6]

In [180]:
def loop_starting_values(smooth_df):
    starting_value_df = get_only_starting_values(smooth_df)

    for i in starting_value_df.iterrows():
        initial_values = [i[1]['acetate'], i[1]['biomass'], i[1]['butanol'], i[1]['butyrate'], i[1]['ethanol']]
        gas_comp = [i[1]['CO'], i[1]['CO2'], i[1]['H2'], i[1]['flow rate']]
        time_range = get_time_range(smooth_df, i[0][0], i[0][1])
        time_list = get_times(smooth_df, i[0][0], i[0][1])
        print(i[0][0], i[0][1], initial_values, gas_comp, time_range, time_list)


In [181]:
# starting_df = get_only_starting_values (smooth_data_6)
loop_starting_values(smooth_data_6)

1 1 [16.90502895927611, 0.4295457013574683, 0.029818099547511474, 0.07552850678733072, 15.895239819004606] [0.5000000000000027, 0.3750000000000019, 0.12500000000000067, 20.00000000000011] [0, 5.6] [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6]
1 2 [15.080408144796461, 0.3895113122171966, 0.18045520361991046, 0.062025339366516184, 16.583848868778368] [0.5000000000000027, 0.3750000000000019, 0.12500000000000067, 20.00000000000011] [0, 5.6] [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6]
2 1 [17.1955701357467, 0.35220995

In [117]:
starting_value_df = get_only_starting_values(smooth_data_6)
starting_value_df

CO    CO2     H2    acetate   biomass   butanol  \
composition trial time                                                       
1           1     0.0   0.500  0.375  0.125  16.905029  0.429546  0.029818   
            2     0.0   0.500  0.375  0.125  15.080408  0.389511  0.180455   
2           1     0.0   0.333  0.250  0.417  17.195570  0.352210  0.067621   
            2     0.0   0.333  0.250  0.417  15.409038  0.369786  0.068179   
3           1     0.0   0.250  0.438  0.313  13.197620  0.279955  0.027778   
            2     0.0   0.250  0.438  0.313  16.198875  0.307353  0.096597   
4           1     0.0   0.500  0.188  0.313   7.442661  0.285756  0.096068   
            2     0.0   0.500  0.188  0.313  11.413597  0.295308  0.085529   
5           1     0.0   0.500  0.375  0.125   6.726022  0.325638  0.016167   
6           1     0.0   0.500  0.188  0.313   8.843519  0.297498  0.031282   
7           1     0.0   0.200  0.000  0.800  19.340291  1.072805  0.134400   
            2     0.0   0.200  0.000  0.800  22.039410  1.196518  0.172751   
8           1     0.0   0.200  0.000  0.800  11.888294  1.087576  0.175151   
            2     0.0   0.200  0.000  0.800  16.428429  1.100393  0.115824   
9           1     0.0   0.200  0.000  0.800  37.871844  1.236729  1.200333   
            2     0.0   0.200  0.000  0.800  29.521730  1.189665  1.026116   

                        butyrate    ethanol  flow rate  acetate_0  biomass_0  \
composition trial time                                                         
1           1     0.0   0.075529  15.895240       20.0  16.905029   0.429546   
            2     0.0   0.062025  16.583849       20.0  15.080408   0.389511   
2           1     0.0   0.157156  21.067346       20.0  17.195570   0.352210   
            2     0.0   0.035988  24.369962       20.0  15.409038   0.369786   
3           1     0.0   0.045570  19.569905       20.0  13.197620   0.279955   
            2     0.0   0.235891  18.896226       20.0  16.198875   0.307353   
4           1     0.0   0.185163  16.390973       20.0   7.442661   0.285756   
            2     0.0   0.142991  16.386493       20.0  11.413597   0.295308   
5           1     0.0   0.110451   5.163814        5.0   6.726022   0.325638   
6           1     0.0   0.173270   5.638690        5.0   8.843519   0.297498   
7           1     0.0   0.319402  14.216557       20.0  19.340291   1.072805   
            2     0.0   1.212669  14.017827       20.0  22.039410   1.196518   
8           1     0.0   0.291138  14.039096       10.0  11.888294   1.087576   
            2     0.0   1.081616  15.648019       10.0  16.428429   1.100393   
9           1     0.0   3.666144  12.956310        1.0  37.871844   1.236729   
            2     0.0   3.133577  14.453932        1.0  29.521730   1.189665   

                        butanol_0  butyrate_0  ethanol_0  acetate_Δ  \
composition trial time                                                
1           1     0.0    0.029818    0.075529  15.895240        0.0   
            2     0.0    0.180455    0.062025  16.583849        0.0   
2           1     0.0    0.067621    0.157156  21.067346        0.0   
            2     0.0    0.068179    0.035988  24.369962        0.0   
3           1     0.0    0.027778    0.045570  19.569905        0.0   
            2     0.0    0.096597    0.235891  18.896226        0.0   
4           1     0.0    0.096068    0.185163  16.390973        0.0   
            2     0.0    0.085529    0.142991  16.386493        0.0   
5           1     0.0    0.016167    0.110451   5.163814        0.0   
6           1     0.0    0.031282    0.173270   5.638690        0.0   
7           1     0.0    0.134400    0.319402  14.216557        0.0   
            2     0.0    0.172751    1.212669  14.017827        0.0   
8           1     0.0    0.175151    0.291138  14.039096        0.0   
            2     0.0    0.115824    1.081616  15.648019        0.0   
9           1     0.0    1.200333    3.666144

In [ ]:


from machine_learning.get_model_metrics import get_pearson_r2, get_rmse

def evaluate_models_6(pred_df_dict, raw_df, metric):
    species_set = ['acetate', 'biomass', 'butanol', 'butyrate', 'ethanol']
    test_comp_set=[1,2,3,4,5,6]
    index_set = ['gradient boosting, raw', 'random forest, raw', 'support vector, raw', 'neural net, raw', 'lasso, raw', 'gradient boosting, smooth', 'random forest, smooth', 'support vector, smooth', 'neural net, smooth', 'lasso, smooth']
    
    for species in species_set:
        data = {}
        for test_comp in test_comp_set:
            data[test_comp] = []
            for model_name in pred_df_dict.keys():
                if str(test_comp) in model_name:
                    predicted_species_values = list(pred_df_dict[model_name].loc[test_comp][species])
                    measured_species_values = list(raw_df.loc[test_comp][species])

                    r2 = get_pearson_r2(measured_species_values, predicted_species_values)
                    rmse = get_rmse (measured_species_values, predicted_species_values)
                    if metric == 'r2':
                        data[test_comp].append(r2)
                    elif metric == 'rmse':
                        data[test_comp].append(rmse)
                    else:
                        print('unknown metric')
        species_data = pd.DataFrame.from_dict(data)
        species_data[f'model for {species}'] = index_set
        species_data.set_index(f'model for {species}', inplace=True, drop=True)
        display(species_data)

def evaluate_models_7(pred_df_dict, raw_df, metric):
    species_set = ['acetate', 'biomass', 'butanol', 'butyrate', 'ethanol']
    test_comp_set=[1,2,3,4,5,6,7]
    index_set = ['gradient boosting, raw', 'random forest, raw', 'support vector, raw', 'neural net, raw', 'lasso, raw', 'gradient boosting, smooth', 'random forest, smooth', 'support vector, smooth', 'neural net, smooth', 'lasso, smooth']
    
    for species in species_set:
        data = {}
        for test_comp in test_comp_set:
            data[test_comp] = []
            for model_name in pred_df_dict.keys():
                # print(model_name)
                if str(test_comp) in model_name:
                    predicted_species_values = list(pred_df_dict[model_name].loc[test_comp][species])
                    measured_species_values = list(raw_df.loc[test_comp][species])

                    r2 = get_pearson_r2(measured_species_values, predicted_species_values)
                    rmse = get_rmse (measured_species_values, predicted_species_values)
                    if metric == 'r2':
                        data[test_comp].append(r2)
                    elif metric == 'rmse':
                        data[test_comp].append(rmse)
                    else:
                        print('unknown metric')
        species_data = pd.DataFrame.from_dict(data)
        species_data[f'model for {species}'] = index_set
        species_data.set_index(f'model for {species}', inplace=True, drop=True)
        display(species_data)

In [ ]:
evaluate_models_6(measured_time_predictions_6, raw_data_6, 'r2')

In [ ]:
evaluate_models_6(measured_time_predictions_6, raw_data_6, 'rmse')

In [ ]:
evaluate_models_7(measured_time_predictions_7, raw_data_7, 'r2')

In [ ]:
evaluate_models_7(measured_time_predictions_7, raw_data_7, 'rmse')

In [ ]:


from machine_learning.get_model_metrics import get_pearson_r2, get_rmse

def validate_models_6(pred_df_dict, raw_df, metric):
    species_set = ['acetate', 'biomass', 'butanol', 'butyrate', 'ethanol']
    test_comp_set=[7, 8, 9]
    index_set = ['gradient boosting, raw', 'random forest, raw', 'support vector, raw', 'neural net, raw', 'lasso, raw', 'gradient boosting, smooth', 'random forest, smooth', 'support vector, smooth', 'neural net, smooth', 'lasso, smooth']
    
    for species in species_set:
        data = {}
        for test_comp in test_comp_set:
            data[test_comp] = []
            for model_name in pred_df_dict.keys():
                if 'none' in model_name:
                    predicted_species_values = list(pred_df_dict[model_name].loc[test_comp][species])
                    measured_species_values = list(raw_df.loc[test_comp][species])

                    r2 = get_pearson_r2(measured_species_values, predicted_species_values)
                    rmse = get_rmse (measured_species_values, predicted_species_values)
                    if metric == 'r2':
                        data[test_comp].append(r2)
                    elif metric == 'rmse':
                        data[test_comp].append(rmse)
                    else:
                        print('unknown metric')
        species_data = pd.DataFrame.from_dict(data)
        species_data[f'model for {species}'] = index_set
        species_data.set_index(f'model for {species}', inplace=True, drop=True)
        display(species_data)

def validate_models_7(pred_df_dict, raw_df, metric):
    species_set = ['acetate', 'biomass', 'butanol', 'butyrate', 'ethanol']
    test_comp_set=[8, 9, 10]
    index_set = ['gradient boosting, raw', 'random forest, raw', 'support vector, raw', 'neural net, raw', 'lasso, raw', 'gradient boosting, smooth', 'random forest, smooth', 'support vector, smooth', 'neural net, smooth', 'lasso, smooth']
    
    for species in species_set:
        data = {}
        for test_comp in test_comp_set:
            data[test_comp] = []
            for model_name in pred_df_dict.keys():
                # print(model_name)
                if 'none' in model_name:
                    predicted_species_values = list(pred_df_dict[model_name].loc[test_comp][species])
                    measured_species_values = list(raw_df.loc[test_comp][species])

                    r2 = get_pearson_r2(measured_species_values, predicted_species_values)
                    rmse = get_rmse (measured_species_values, predicted_species_values)
                    if metric == 'r2':
                        data[test_comp].append(r2)
                    elif metric == 'rmse':
                        data[test_comp].append(rmse)
                    else:
                        print('unknown metric')
        species_data = pd.DataFrame.from_dict(data)
        species_data[f'model for {species}'] = index_set
        species_data.set_index(f'model for {species}', inplace=True, drop=True)
        display(species_data)

In [ ]:
validate_models_6(measured_time_predictions_6, raw_data_6, 'r2')

In [ ]:
validate_models_6(measured_time_predictions_6, raw_data_6, 'rmse')

In [ ]:
validate_models_7(measured_time_predictions_7, raw_data_7, 'r2')

In [ ]:
validate_models_7(measured_time_predictions_7, raw_data_7, 'rmse')

In [ ]:
smoothed_time_predictions_6['gradient boosting, smooth, test comp = none'].loc[[7,8,9]].to_csv(f'{cur_dir}/outputs/gb_smooth_val_6.csv')
smoothed_time_predictions_7['gradient boosting, smooth, test comp = none'].loc[[8,9,10]].to_csv(f'{cur_dir}/outputs/gb_smooth_val_7.csv')